#!/bin/bash

command="$1"

data_branch="ci/persistent-storage"
remote_url="$(git config --get remote.origin.url)"
root_dir="$(git rev-parse --show-toplevel)"

pushd "$root_dir" &>/dev/null || exit 1

set_git_config () {
    git config --global user.name "CI Storage"
    git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
}

shopt -s nocasematch
case "$command" in
  path)
      echo "$(pwd)"/.ci-storage
      ;;

  get)
     echo "Setting up .ci-storage for $remote_url"
     git pull

     git ls-remote --exit-code origin "$data_branch" >/dev/null 2>&1
     exit_code=$?

      if [ ${exit_code} -ne 0 ]
      then
          git checkout -b "$data_branch"
          # if the branch didn't exist, make sure it's empty
          # this is because the files in here are for storing data across CI runs
          # and not for the actual codebase
          git rm -rf *
          git rm -rf .github
          git rm .gitignore

          mkdir -p .ci-storage
          touch .ci-storage/.gitkeep

          set_git_config

          git add .ci-storage
          git commit -m "init"
          git push origin "$data_branch"
          git checkout -
      fi
      git checkout origin/"$data_branch" -- .ci-storage
    ;;

  persist)
      git checkout "$data_branch"

      set_git_config

      git add .ci-storage
      git commit -m "update"
      git push origin "$data_branch"
    ;;

  *)
    echo "Invalid command"
    exit 1
    ;;
esac

popd &>/dev/null || exit 1